export const GET_ACTIVE_REQUEST = 'GET_ACTIVE_REQUEST'
export const GET_ACTIVE_SUCCESS = 'GET_ACTIVE_SUCCESS'

export const POST_ADD_TICKET_REQUEST = 'POST_ADD_TICKET_REQUEST'
export const POST_ADD_TICKET_SUCCESS = 'POST_ADD_TICKET_SUCCESS'

export const PATCH_UPDATE_TICKET_SUCCESS = 'PATCH_UPDATE_TICKET_SUCCESS'
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS'