export const GET_TERMS = 'GET_TERMS'
export const GET_ACTIVE_REQUEST = 'GET_ACTIVE_REQUEST'
export const GET_ACTIVE_SUCCESS = 'GET_ACTIVE_SUCCESS'

export const POST_ADD_TICKET_REQUEST = 'POST_ADD_TICKET_REQUEST'
export const POST_ADD_TICKET_SUCCESS = 'POST_ADD_TICKET_SUCCESS'
export const POST_ADD_TICKET_ERROR = 'POST_ADD_TICKET_ERROR'

export const POST_ADD_TICKET_SR_SUCCESS = 'POST_ADD_TICKET_SR_SUCCESS'

export const PATCH_TERMS_AGREE = 'PATCH_TERMS_AGREE'
export const PATCH_SUBMIT_FINAL = 'PATCH_SUBMIT_FINAL'

export const PATCH_UPDATE_TICKET_SUCCESS = 'PATCH_UPDATE_TICKET_SUCCESS'
export const PATCH_UPDATE_TICKET_ERROR = 'PATCH_UPDATE_TICKET_ERROR'

export const PATCH_UPDATE_TICKET_SR_SUCCESS = 'PATCH_UPDATE_TICKET_SR_SUCCESS'
export const PATCH_UPDATE_TICKET_SR_ERROR = 'PATCH_UPDATE_TICKET_SR_ERROR'

export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS'
export const DELETE_TICKET_SR_SUCCESS = 'DELETE_TICKET_SR_SUCCESS'
export const ON_OFF_EDIT_TICKET_FORM = 'ON_OFF_EDIT_TICKET_FORM'
export const ON_OFF_EDIT_TICKET_SR_FORM = 'ON_OFF_EDIT_TICKET_SR_FORM'
export const CLEAR_ADD_TICKET_ERROR = 'CLEAR_ADD_TICKET_ERROR'
