export const SWITCH_TAB = 'SWITCH_TAB'
export const SET_COMPLETED_COUNT_SUCCESS = 'SET_COMPLETED_COUNT_SUCCESS'

export const SET_MATERIALS_SUCCESS = 'SET_MATERIALS_SUCCESS'
export const SET_SALVAGE_MATERIALS_SUCCESS = 'SET_SALVAGE_MATERIALS_SUCCESS'

export const SET_FACILITIES_REQUEST = 'SET_FACILITIES_REQUEST'
export const SET_SALVAGE_FACILITIES_SUCCESS = 'SET_SALVAGE_FACILITIES_SUCCESS'
export const SET_FACILITIES_SUCCESS = 'SET_FACILITIES_SUCCESS'