export const SWITCH_TAB = 'SWITCH_TAB'

export const GET_RECYCLING_TOTALS_SUCCESS = 'GET_RECYCLING_TOTALS_SUCCESS'
export const GET_CARBON_FOOTPRINT_SUCCESS = 'GET_CARBON_FOOTPRINT_SUCCESS'

export const GET_MATERIALS_STATS_SUCCESS = 'GET_MATERIALS_STATS_SUCCESS'
export const GET_FACILITIES_STATS_SUCCESS = 'GET_FACILITIES_STATS_SUCCESS'
export const GET_PROJECTS_STATS_SUCCESS = 'GET_PROJECTS_STATS_SUCCESS'
export const GET_BUILDINGS_STATS_SUCCESS = 'GET_BUILDINGS_STATS_SUCCESS'
export const GET_HAULING_STATS_SUCCESS = 'GET_HAULING_STATS_SUCCESS'

export const SET_DATE_RANGE = 'SET_DATE_RANGE'